<?php

namespace ContainerWhTVkGK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_9if3UAsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.9if3UAs' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9if3UAs'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\Admin\\AdminController::affCategorie' => ['privates', '.service_locator.nSLHan9', 'get_ServiceLocator_NSLHan9Service', true],
            'App\\Controller\\Admin\\AdminController::affUser' => ['privates', '.service_locator.RTUGCCW', 'get_ServiceLocator_RTUGCCWService', true],
            'App\\Controller\\Admin\\AdminController::ajouterCategorie' => ['privates', '.service_locator.O30o4K4', 'get_ServiceLocator_O30o4K4Service', true],
            'App\\Controller\\Admin\\AdminController::deleteUser' => ['privates', '.service_locator.dNCO0Nf', 'get_ServiceLocator_DNCO0NfService', true],
            'App\\Controller\\Admin\\AdminController::editUser' => ['privates', '.service_locator.dNCO0Nf', 'get_ServiceLocator_DNCO0NfService', true],
            'App\\Controller\\CategorieController::delete' => ['privates', '.service_locator.57pSehj', 'get_ServiceLocator_57pSehjService', true],
            'App\\Controller\\CategorieController::edit' => ['privates', '.service_locator.57pSehj', 'get_ServiceLocator_57pSehjService', true],
            'App\\Controller\\CategorieController::index' => ['privates', '.service_locator.9aMSQQN', 'get_ServiceLocator_9aMSQQNService', true],
            'App\\Controller\\CategorieController::show' => ['privates', '.service_locator.57pSehj', 'get_ServiceLocator_57pSehjService', true],
            'App\\Controller\\RegistrationController::editAccount' => ['privates', '.service_locator.0l1nthY', 'get_ServiceLocator_0l1nthYService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.j5_bHjD', 'get_ServiceLocator_J5BHjDService', true],
            'App\\Controller\\ResetPasswordController::request' => ['privates', '.service_locator.A0rcl1e', 'get_ServiceLocator_A0rcl1eService', true],
            'App\\Controller\\ResetPasswordController::reset' => ['privates', '.service_locator.j5_bHjD', 'get_ServiceLocator_J5BHjDService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.xA8Fw_.', 'get_ServiceLocator_XA8Fw_Service', true],
            'App\\Controller\\User\\UserController::editUser' => ['privates', '.service_locator.dNCO0Nf', 'get_ServiceLocator_DNCO0NfService', true],
            'App\\Controller\\User\\UserController::getInfosUser' => ['privates', '.service_locator.fw6ySEy', 'get_ServiceLocator_Fw6ySEyService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'App\\Controller\\Admin\\AdminController:affCategorie' => ['privates', '.service_locator.nSLHan9', 'get_ServiceLocator_NSLHan9Service', true],
            'App\\Controller\\Admin\\AdminController:affUser' => ['privates', '.service_locator.RTUGCCW', 'get_ServiceLocator_RTUGCCWService', true],
            'App\\Controller\\Admin\\AdminController:ajouterCategorie' => ['privates', '.service_locator.O30o4K4', 'get_ServiceLocator_O30o4K4Service', true],
            'App\\Controller\\Admin\\AdminController:deleteUser' => ['privates', '.service_locator.dNCO0Nf', 'get_ServiceLocator_DNCO0NfService', true],
            'App\\Controller\\Admin\\AdminController:editUser' => ['privates', '.service_locator.dNCO0Nf', 'get_ServiceLocator_DNCO0NfService', true],
            'App\\Controller\\CategorieController:delete' => ['privates', '.service_locator.57pSehj', 'get_ServiceLocator_57pSehjService', true],
            'App\\Controller\\CategorieController:edit' => ['privates', '.service_locator.57pSehj', 'get_ServiceLocator_57pSehjService', true],
            'App\\Controller\\CategorieController:index' => ['privates', '.service_locator.9aMSQQN', 'get_ServiceLocator_9aMSQQNService', true],
            'App\\Controller\\CategorieController:show' => ['privates', '.service_locator.57pSehj', 'get_ServiceLocator_57pSehjService', true],
            'App\\Controller\\RegistrationController:editAccount' => ['privates', '.service_locator.0l1nthY', 'get_ServiceLocator_0l1nthYService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.j5_bHjD', 'get_ServiceLocator_J5BHjDService', true],
            'App\\Controller\\ResetPasswordController:request' => ['privates', '.service_locator.A0rcl1e', 'get_ServiceLocator_A0rcl1eService', true],
            'App\\Controller\\ResetPasswordController:reset' => ['privates', '.service_locator.j5_bHjD', 'get_ServiceLocator_J5BHjDService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.xA8Fw_.', 'get_ServiceLocator_XA8Fw_Service', true],
            'App\\Controller\\User\\UserController:editUser' => ['privates', '.service_locator.dNCO0Nf', 'get_ServiceLocator_DNCO0NfService', true],
            'App\\Controller\\User\\UserController:getInfosUser' => ['privates', '.service_locator.fw6ySEy', 'get_ServiceLocator_Fw6ySEyService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
        ], [
            'App\\Controller\\Admin\\AdminController::affCategorie' => '?',
            'App\\Controller\\Admin\\AdminController::affUser' => '?',
            'App\\Controller\\Admin\\AdminController::ajouterCategorie' => '?',
            'App\\Controller\\Admin\\AdminController::deleteUser' => '?',
            'App\\Controller\\Admin\\AdminController::editUser' => '?',
            'App\\Controller\\CategorieController::delete' => '?',
            'App\\Controller\\CategorieController::edit' => '?',
            'App\\Controller\\CategorieController::index' => '?',
            'App\\Controller\\CategorieController::show' => '?',
            'App\\Controller\\RegistrationController::editAccount' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\ResetPasswordController::request' => '?',
            'App\\Controller\\ResetPasswordController::reset' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\User\\UserController::editUser' => '?',
            'App\\Controller\\User\\UserController::getInfosUser' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\Admin\\AdminController:affCategorie' => '?',
            'App\\Controller\\Admin\\AdminController:affUser' => '?',
            'App\\Controller\\Admin\\AdminController:ajouterCategorie' => '?',
            'App\\Controller\\Admin\\AdminController:deleteUser' => '?',
            'App\\Controller\\Admin\\AdminController:editUser' => '?',
            'App\\Controller\\CategorieController:delete' => '?',
            'App\\Controller\\CategorieController:edit' => '?',
            'App\\Controller\\CategorieController:index' => '?',
            'App\\Controller\\CategorieController:show' => '?',
            'App\\Controller\\RegistrationController:editAccount' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\ResetPasswordController:request' => '?',
            'App\\Controller\\ResetPasswordController:reset' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\User\\UserController:editUser' => '?',
            'App\\Controller\\User\\UserController:getInfosUser' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
