<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUW6LTtT\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUW6LTtT/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUW6LTtT.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUW6LTtT\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUW6LTtT\App_KernelDevDebugContainer([
    'container.build_hash' => 'UW6LTtT',
    'container.build_id' => '57b10ab1',
    'container.build_time' => 1605625228,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUW6LTtT');
