<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWsyX5Og\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWsyX5Og/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWsyX5Og.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWsyX5Og\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWsyX5Og\App_KernelDevDebugContainer([
    'container.build_hash' => 'WsyX5Og',
    'container.build_id' => '59f7c8e3',
    'container.build_time' => 1605532368,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWsyX5Og');
